### ISSUE TITLE
validate panic's with an attempt to subtract with overflow

### ISSUE THREAD

**Issue by cholcombe973** [MarcusGrass/http-range-header#7]
https://github.com/MarcusGrass/http-range-header/blob/194fad909405c8cba9b1f1e69b90760186cc727c/src/lib.rs#L242
I have some code that apparently isn't very smart and passes in a zero to the validate function causing that subtraction to blow up. 
I can setup a PR if you like. The fix is super easy.

**Comment by MarcusGrass** [comment]
Released at 0.4.1!
