### ISSUE TITLE
Parse without knowing the file size

### ISSUE THREAD

**Issue by cetra3** [MarcusGrass/http-range-header#9]
I have a scenario where I am passing on the range request to a downstream service, where I don't know what the total size is.

Unfortunately as this crate stands, there is no way to parse the file header and return the ranges within it.  `SyntacticallyCorrectRange` is private and so is the `ranges` field of `ParsedRanges`. Is there a reason to not make these public?

**Comment by MarcusGrass** [comment]
> I have a scenario where I am passing on the range request to a downstream service, where I don't know what the total size is.
> 
> Unfortunately as this crate stands, there is no way to parse the file header and return the ranges within it.  `SyntacticallyCorrectRange` is private and so is the `ranges` field of `ParsedRanges`. Is there a reason to not make these public?

I see, there's no real reason that it's private other than that we didn't need it to be public for our use case. 

I currently have very limited time to work on things in general, but this shouldn't be a difficult to fix. First off though, how about wrapping the arguments that you're passing down with the size from where you have access to it in some small struct?

**Comment by cetra3** [comment]
I need to parse the header directly, given how the code is structured, as we are converting that into a request to a downstream service, where we don't know the full size of the file ahead of time.  I've raised a PR to make a few of these things public: https://github.com/MarcusGrass/http-range-header/pull/10

**Comment by MarcusGrass** [comment]
0.4.2 is released https://crates.io/crates/http-range-header/0.4.2!
Thank you for your contribution!
